version: "3.1"

services:
  accountdb:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - app-network

  account:
    build: .
    container_name: account-service
    restart: always
    ports:
      - 80:3000
    environment:
      - DATABASEURI="host=salt.db.elephantsql.com user=pvhdolsp dbname=pvhdolsp password=WPSXt41F15pPgpTx-0V7CC6Ec5ALoyvL sslmode=disable"
      - PORT=3000
      - SECRETKEY="accountN9"
    depends_on:
      - accountdb
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db-data:
