// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api.proto

package api

import (
	context "context"
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/golang/protobuf/proto"
	model "github.com/nirajgeorgian/account/src/model"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// create an account
type CreateAccountReq struct {
	Account              *model.Account `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *CreateAccountReq) Reset()         { *m = CreateAccountReq{} }
func (m *CreateAccountReq) String() string { return proto.CompactTextString(m) }
func (*CreateAccountReq) ProtoMessage()    {}
func (*CreateAccountReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{0}
}

func (m *CreateAccountReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateAccountReq.Unmarshal(m, b)
}
func (m *CreateAccountReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateAccountReq.Marshal(b, m, deterministic)
}
func (m *CreateAccountReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateAccountReq.Merge(m, src)
}
func (m *CreateAccountReq) XXX_Size() int {
	return xxx_messageInfo_CreateAccountReq.Size(m)
}
func (m *CreateAccountReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateAccountReq.DiscardUnknown(m)
}

var xxx_messageInfo_CreateAccountReq proto.InternalMessageInfo

func (m *CreateAccountReq) GetAccount() *model.Account {
	if m != nil {
		return m.Account
	}
	return nil
}

type CreateAccountRes struct {
	Account              *model.Account `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *CreateAccountRes) Reset()         { *m = CreateAccountRes{} }
func (m *CreateAccountRes) String() string { return proto.CompactTextString(m) }
func (*CreateAccountRes) ProtoMessage()    {}
func (*CreateAccountRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{1}
}

func (m *CreateAccountRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateAccountRes.Unmarshal(m, b)
}
func (m *CreateAccountRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateAccountRes.Marshal(b, m, deterministic)
}
func (m *CreateAccountRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateAccountRes.Merge(m, src)
}
func (m *CreateAccountRes) XXX_Size() int {
	return xxx_messageInfo_CreateAccountRes.Size(m)
}
func (m *CreateAccountRes) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateAccountRes.DiscardUnknown(m)
}

var xxx_messageInfo_CreateAccountRes proto.InternalMessageInfo

func (m *CreateAccountRes) GetAccount() *model.Account {
	if m != nil {
		return m.Account
	}
	return nil
}

// read an account
type ReadAccountReq struct {
	AccountId            string   `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadAccountReq) Reset()         { *m = ReadAccountReq{} }
func (m *ReadAccountReq) String() string { return proto.CompactTextString(m) }
func (*ReadAccountReq) ProtoMessage()    {}
func (*ReadAccountReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{2}
}

func (m *ReadAccountReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadAccountReq.Unmarshal(m, b)
}
func (m *ReadAccountReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadAccountReq.Marshal(b, m, deterministic)
}
func (m *ReadAccountReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadAccountReq.Merge(m, src)
}
func (m *ReadAccountReq) XXX_Size() int {
	return xxx_messageInfo_ReadAccountReq.Size(m)
}
func (m *ReadAccountReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadAccountReq.DiscardUnknown(m)
}

var xxx_messageInfo_ReadAccountReq proto.InternalMessageInfo

func (m *ReadAccountReq) GetAccountId() string {
	if m != nil {
		return m.AccountId
	}
	return ""
}

type ReadAccountRes struct {
	Account              *model.Account `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ReadAccountRes) Reset()         { *m = ReadAccountRes{} }
func (m *ReadAccountRes) String() string { return proto.CompactTextString(m) }
func (*ReadAccountRes) ProtoMessage()    {}
func (*ReadAccountRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{3}
}

func (m *ReadAccountRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadAccountRes.Unmarshal(m, b)
}
func (m *ReadAccountRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadAccountRes.Marshal(b, m, deterministic)
}
func (m *ReadAccountRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadAccountRes.Merge(m, src)
}
func (m *ReadAccountRes) XXX_Size() int {
	return xxx_messageInfo_ReadAccountRes.Size(m)
}
func (m *ReadAccountRes) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadAccountRes.DiscardUnknown(m)
}

var xxx_messageInfo_ReadAccountRes proto.InternalMessageInfo

func (m *ReadAccountRes) GetAccount() *model.Account {
	if m != nil {
		return m.Account
	}
	return nil
}

// update an account
type UpdateAccountReq struct {
	Account              *model.Account `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *UpdateAccountReq) Reset()         { *m = UpdateAccountReq{} }
func (m *UpdateAccountReq) String() string { return proto.CompactTextString(m) }
func (*UpdateAccountReq) ProtoMessage()    {}
func (*UpdateAccountReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{4}
}

func (m *UpdateAccountReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateAccountReq.Unmarshal(m, b)
}
func (m *UpdateAccountReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateAccountReq.Marshal(b, m, deterministic)
}
func (m *UpdateAccountReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateAccountReq.Merge(m, src)
}
func (m *UpdateAccountReq) XXX_Size() int {
	return xxx_messageInfo_UpdateAccountReq.Size(m)
}
func (m *UpdateAccountReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateAccountReq.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateAccountReq proto.InternalMessageInfo

func (m *UpdateAccountReq) GetAccount() *model.Account {
	if m != nil {
		return m.Account
	}
	return nil
}

type UpdateAccountRes struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateAccountRes) Reset()         { *m = UpdateAccountRes{} }
func (m *UpdateAccountRes) String() string { return proto.CompactTextString(m) }
func (*UpdateAccountRes) ProtoMessage()    {}
func (*UpdateAccountRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{5}
}

func (m *UpdateAccountRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateAccountRes.Unmarshal(m, b)
}
func (m *UpdateAccountRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateAccountRes.Marshal(b, m, deterministic)
}
func (m *UpdateAccountRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateAccountRes.Merge(m, src)
}
func (m *UpdateAccountRes) XXX_Size() int {
	return xxx_messageInfo_UpdateAccountRes.Size(m)
}
func (m *UpdateAccountRes) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateAccountRes.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateAccountRes proto.InternalMessageInfo

func (m *UpdateAccountRes) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

// delete an account
type DeleteAccountReq struct {
	AccountId            string   `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteAccountReq) Reset()         { *m = DeleteAccountReq{} }
func (m *DeleteAccountReq) String() string { return proto.CompactTextString(m) }
func (*DeleteAccountReq) ProtoMessage()    {}
func (*DeleteAccountReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{6}
}

func (m *DeleteAccountReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteAccountReq.Unmarshal(m, b)
}
func (m *DeleteAccountReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteAccountReq.Marshal(b, m, deterministic)
}
func (m *DeleteAccountReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteAccountReq.Merge(m, src)
}
func (m *DeleteAccountReq) XXX_Size() int {
	return xxx_messageInfo_DeleteAccountReq.Size(m)
}
func (m *DeleteAccountReq) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteAccountReq.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteAccountReq proto.InternalMessageInfo

func (m *DeleteAccountReq) GetAccountId() string {
	if m != nil {
		return m.AccountId
	}
	return ""
}

type DeleteAccountRes struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteAccountRes) Reset()         { *m = DeleteAccountRes{} }
func (m *DeleteAccountRes) String() string { return proto.CompactTextString(m) }
func (*DeleteAccountRes) ProtoMessage()    {}
func (*DeleteAccountRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{7}
}

func (m *DeleteAccountRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteAccountRes.Unmarshal(m, b)
}
func (m *DeleteAccountRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteAccountRes.Marshal(b, m, deterministic)
}
func (m *DeleteAccountRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteAccountRes.Merge(m, src)
}
func (m *DeleteAccountRes) XXX_Size() int {
	return xxx_messageInfo_DeleteAccountRes.Size(m)
}
func (m *DeleteAccountRes) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteAccountRes.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteAccountRes proto.InternalMessageInfo

func (m *DeleteAccountRes) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func init() {
	proto.RegisterType((*CreateAccountReq)(nil), "account.CreateAccountReq")
	proto.RegisterType((*CreateAccountRes)(nil), "account.CreateAccountRes")
	proto.RegisterType((*ReadAccountReq)(nil), "account.ReadAccountReq")
	proto.RegisterType((*ReadAccountRes)(nil), "account.ReadAccountRes")
	proto.RegisterType((*UpdateAccountReq)(nil), "account.UpdateAccountReq")
	proto.RegisterType((*UpdateAccountRes)(nil), "account.UpdateAccountRes")
	proto.RegisterType((*DeleteAccountReq)(nil), "account.DeleteAccountReq")
	proto.RegisterType((*DeleteAccountRes)(nil), "account.DeleteAccountRes")
}

func init() { proto.RegisterFile("api.proto", fileDescriptor_00212fb1f9d3bf1c) }

var fileDescriptor_00212fb1f9d3bf1c = []byte{
	// 315 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x92, 0xc1, 0x4e, 0xbb, 0x40,
	0x10, 0xc6, 0xcb, 0xe5, 0xdf, 0x7f, 0xa7, 0x69, 0x43, 0xf6, 0x62, 0x25, 0xd1, 0x18, 0x4e, 0xc6,
	0x20, 0x1b, 0xf1, 0xa8, 0x31, 0xa9, 0x9a, 0x34, 0x5e, 0x31, 0x5e, 0xbc, 0x98, 0x65, 0x19, 0x71,
	0x4d, 0xcb, 0xe2, 0x2e, 0xf8, 0x7c, 0xbe, 0x8b, 0xf1, 0x3d, 0x8c, 0x0b, 0x34, 0x40, 0x45, 0x53,
	0x6f, 0x7c, 0x7c, 0xf3, 0x9b, 0xd9, 0xd9, 0x6f, 0x61, 0xc4, 0x32, 0xe1, 0x67, 0x4a, 0xe6, 0x92,
	0x0c, 0x19, 0xe7, 0xb2, 0x48, 0x73, 0xe7, 0x38, 0x11, 0xf9, 0x53, 0x11, 0xf9, 0x5c, 0xae, 0x68,
	0x22, 0x13, 0x49, 0x8d, 0x1f, 0x15, 0x8f, 0x46, 0x19, 0x61, 0xbe, 0x4a, 0xce, 0x19, 0xaf, 0x64,
	0x8c, 0xcb, 0x52, 0xb8, 0x17, 0x60, 0x5f, 0x29, 0x64, 0x39, 0xce, 0xcb, 0x66, 0x21, 0xbe, 0x90,
	0x23, 0xa8, 0x5b, 0xcf, 0xac, 0x03, 0xeb, 0x70, 0x1c, 0xd8, 0x7e, 0xa5, 0xfd, 0xba, 0xaa, 0x2e,
	0xf8, 0x86, 0xd7, 0x5b, 0xf1, 0x14, 0xa6, 0x21, 0xb2, 0xb8, 0x31, 0x7d, 0x0f, 0xa0, 0x32, 0x1f,
	0x44, 0x6c, 0x1a, 0x8c, 0xc2, 0x51, 0xf5, 0xe7, 0x26, 0x76, 0xcf, 0x3b, 0x80, 0xde, 0xf6, 0xb8,
	0x77, 0x59, 0xfc, 0xf7, 0x75, 0xbd, 0x0d, 0x5e, 0x93, 0x19, 0x0c, 0x75, 0xc1, 0x39, 0x6a, 0x6d,
	0xf8, 0xff, 0x61, 0x2d, 0xdd, 0x13, 0xb0, 0xaf, 0x71, 0x89, 0xad, 0x69, 0xbf, 0xac, 0xe7, 0x6d,
	0x20, 0x3f, 0x0c, 0x08, 0x3e, 0x2c, 0x98, 0x56, 0x85, 0xb7, 0xa8, 0x5e, 0x05, 0x47, 0xb2, 0x80,
	0x49, 0x2b, 0x10, 0xb2, 0xbb, 0xde, 0xa6, 0x1b, 0xb4, 0xd3, 0x6b, 0x69, 0x77, 0x40, 0xe6, 0x30,
	0x6e, 0x5c, 0x34, 0xd9, 0x59, 0xd7, 0xb6, 0xf3, 0x72, 0x7a, 0x8c, 0xaf, 0x16, 0x0b, 0x98, 0xb4,
	0x6e, 0xab, 0x71, 0x96, 0x6e, 0x0a, 0x4e, 0xaf, 0xa5, 0xdd, 0xc1, 0x65, 0xf0, 0xf6, 0xbe, 0x6f,
	0xdd, 0x7b, 0x8d, 0x77, 0x9e, 0x0a, 0xc5, 0x9e, 0x13, 0x94, 0x2a, 0x11, 0x2c, 0xa5, 0x15, 0x4a,
	0xb5, 0xe2, 0x94, 0x65, 0xe2, 0x8c, 0x65, 0x22, 0xfa, 0x67, 0x1e, 0xf8, 0xe9, 0x67, 0x00, 0x00,
	0x00, 0xff, 0xff, 0x99, 0x15, 0x70, 0xcd, 0x32, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AccountServiceClient is the client API for AccountService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AccountServiceClient interface {
	CreateAccount(ctx context.Context, in *CreateAccountReq, opts ...grpc.CallOption) (*CreateAccountRes, error)
	ReadAccount(ctx context.Context, in *ReadAccountReq, opts ...grpc.CallOption) (*ReadAccountRes, error)
	UpdateAccount(ctx context.Context, in *UpdateAccountReq, opts ...grpc.CallOption) (*UpdateAccountRes, error)
}

type accountServiceClient struct {
	cc *grpc.ClientConn
}

func NewAccountServiceClient(cc *grpc.ClientConn) AccountServiceClient {
	return &accountServiceClient{cc}
}

func (c *accountServiceClient) CreateAccount(ctx context.Context, in *CreateAccountReq, opts ...grpc.CallOption) (*CreateAccountRes, error) {
	out := new(CreateAccountRes)
	err := c.cc.Invoke(ctx, "/account.AccountService/CreateAccount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) ReadAccount(ctx context.Context, in *ReadAccountReq, opts ...grpc.CallOption) (*ReadAccountRes, error) {
	out := new(ReadAccountRes)
	err := c.cc.Invoke(ctx, "/account.AccountService/ReadAccount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) UpdateAccount(ctx context.Context, in *UpdateAccountReq, opts ...grpc.CallOption) (*UpdateAccountRes, error) {
	out := new(UpdateAccountRes)
	err := c.cc.Invoke(ctx, "/account.AccountService/UpdateAccount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AccountServiceServer is the server API for AccountService service.
type AccountServiceServer interface {
	CreateAccount(context.Context, *CreateAccountReq) (*CreateAccountRes, error)
	ReadAccount(context.Context, *ReadAccountReq) (*ReadAccountRes, error)
	UpdateAccount(context.Context, *UpdateAccountReq) (*UpdateAccountRes, error)
}

func RegisterAccountServiceServer(s *grpc.Server, srv AccountServiceServer) {
	s.RegisterService(&_AccountService_serviceDesc, srv)
}

func _AccountService_CreateAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAccountReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).CreateAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/account.AccountService/CreateAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).CreateAccount(ctx, req.(*CreateAccountReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_ReadAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadAccountReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).ReadAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/account.AccountService/ReadAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).ReadAccount(ctx, req.(*ReadAccountReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_UpdateAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateAccountReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).UpdateAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/account.AccountService/UpdateAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).UpdateAccount(ctx, req.(*UpdateAccountReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _AccountService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "account.AccountService",
	HandlerType: (*AccountServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateAccount",
			Handler:    _AccountService_CreateAccount_Handler,
		},
		{
			MethodName: "ReadAccount",
			Handler:    _AccountService_ReadAccount_Handler,
		},
		{
			MethodName: "UpdateAccount",
			Handler:    _AccountService_UpdateAccount_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api.proto",
}
